[alpha-nvim]
fetch.github = "goolord/alpha-nvim"
src.git = "https://github.com/goolord/alpha-nvim"

[catppuccin]
fetch.github = "catppuccin/nvim"
src.git = "https://github.com/catppuccin/nvim"

[freeze-nvim]
fetch.github = "charm-community/freeze.nvim"
src.git = "https://github.com/charm-community/freeze.nvim"

[cloak]
fetch.github = "laytan/cloak.nvim"
src.git = "https://github.com/laytan/cloak.nvim"

[cmp-buffer]
fetch.github = "hrsh7th/cmp-buffer"
src.git = "https://github.com/hrsh7th/cmp-buffer"

[cmp-cmdline]
fetch.github = "hrsh7th/cmp-cmdline"
src.git = "https://github.com/hrsh7th/cmp-cmdline"

[cmp-nvim-lsp]
fetch.github = "hrsh7th/cmp-nvim-lsp"
src.git = "https://github.com/hrsh7th/cmp-nvim-lsp"

[cmp-path]
fetch.github = "hrsh7th/cmp-path"
src.git = "https://github.com/hrsh7th/cmp-path"

[cmp_luasnip]
fetch.github = "saadparwaiz1/cmp_luasnip"
src.git = "https://github.com/saadparwaiz1/cmp_luasnip"

[copilot-lua]
fetch.github = "zbirenbaum/copilot.lua"
src.git = "https://github.com/zbirenbaum/copilot.lua"

[copilot-cmp]
fetch.github = "zbirenbaum/copilot-cmp"
src.git = "https://github.com/zbirenbaum/copilot-cmp"

[crates]
fetch.github = "saecki/crates.nvim"
src.git = "https://github.com/saecki/crates.nvim"

[editorconfig]
fetch.github = "gpanders/editorconfig.nvim"
src.git = "https://github.com/gpanders/editorconfig.nvim"

[fidget]
fetch.github = "j-hui/fidget.nvim"
src.git = "https://github.com/j-hui/fidget.nvim"
src.branch = "legacy"

[go-nvim]
fetch.github = "ray-x/go.nvim"
src.git = "https://github.com/ray-x/go.nvim"

[guihua-lua]
fetch.github = "ray-x/guihua.lua"
src.git = "https://github.com/ray-x/guihua.lua"

[harpoon]
fetch.github = "ThePrimeagen/harpoon"
src.git = "https://github.com/ThePrimeagen/harpoon"
src.branch = "harpoon2"

[lazy]
fetch.github = "folke/lazy.nvim"
src.git = "https://github.com/folke/lazy.nvim"

[lazygit]
fetch.github = "kdheepak/lazygit.nvim"
src.git = "https://github.com/kdheepak/lazygit.nvim"

[lsp-status]
fetch.github = "nvim-lua/lsp-status.nvim"
src.git = "https://github.com/nvim-lua/lsp-status.nvim"

[lspkind]
fetch.github = "onsails/lspkind.nvim"
src.git = "https://github.com/onsails/lspkind.nvim"

[ltex-extra]
fetch.github = "barreiroleo/ltex-extra.nvim"
src.git = "https://github.com/barreiroleo/ltex-extra.nvim"

[lualine]
fetch.github = "nvim-lualine/lualine.nvim"
src.git = "https://github.com/nvim-lualine/lualine.nvim"

[luasnip]
fetch.github = "L3MON4D3/LuaSnip"
src.git = "https://github.com/L3MON4D3/LuaSnip"

[indent-blankline]
fetch.github = "lukas-reineke/indent-blankline.nvim"
src.git = "https://github.com/lukas-reineke/indent-blankline.nvim"

[neodev]
fetch.github = "folke/neodev.nvim"
src.git = "https://github.com/folke/neodev.nvim"

[neovim-session-manager]
fetch.github = "Shatur/neovim-session-manager"
src.git = "https://github.com/Shatur/neovim-session-manager"

[null-ls]
fetch.github = "nvimtools/none-ls.nvim"
src.git = "https://github.com/nvimtools/none-ls.nvim"

[nvim-cmp]
fetch.github = "hrsh7th/nvim-cmp"
src.git = "https://github.com/hrsh7th/nvim-cmp"

[nvim-colorizer-lua]
fetch.github = "nvchad/nvim-colorizer.lua"
src.git = "https://github.com/nvchad/nvim-colorizer.lua"

[nvim-lspconfig]
fetch.github = "neovim/nvim-lspconfig"
src.git = "https://github.com/neovim/nvim-lspconfig"

[nvim-navic]
fetch.github = "SmiteshP/nvim-navic"
src.git = "https://github.com/SmiteshP/nvim-navic"

[nvim-notify]
fetch.github = "rcarriga/nvim-notify"
src.git = "https://github.com/rcarriga/nvim-notify"

[nvim-tree-lua]
fetch.github = "nvim-tree/nvim-tree.lua"
src.git = "https://github.com/nvim-tree/nvim-tree.lua"

[nvim-treesitter]
fetch.github = "nvim-treesitter/nvim-treesitter"
src.git = "https://github.com/nvim-treesitter/nvim-treesitter"

[nvim-web-devicons]
fetch.github = "nvim-tree/nvim-web-devicons"
src.git = "https://github.com/nvim-tree/nvim-web-devicons"

[obsidian-nvim]
fetch.github = "epwalsh/obsidian.nvim"
src.git = "https://github.com/epwalsh/obsidian.nvim"

[plenary]
fetch.github = "nvim-lua/plenary.nvim"
src.git = "https://github.com/nvim-lua/plenary.nvim"

[presence]
fetch.github = "andweeb/presence.nvim"
src.git = "https://github.com/andweeb/presence.nvim"

[py_lsp]
fetch.github = "hallerpatrick/py_lsp.nvim"
src.git = "https://github.com/hallerpatrick/py_lsp.nvim"

[rainbow-delimiters]
fetch.github = "hiphish/rainbow-delimiters.nvim"
src.git = "https://github.com/hiphish/rainbow-delimiters.nvim"

[rustaceanvim]
fetch.github = "mrcjkb/rustaceanvim"
src.git = "https://github.com/mrcjkb/rustaceanvim"

[rust-vim]
fetch.github = "rust-lang/rust.vim"
src.git = "https://github.com/rust-lang/rust.vim"

[schemastore]
fetch.github = "b0o/schemastore.nvim"
src.git = "https://github.com/b0o/schemastore.nvim"

[telescope]
fetch.github = "nvim-telescope/telescope.nvim"
src.git = "https://github.com/nvim-telescope/telescope.nvim"

[telescope-file-browser]
fetch.github = "nvim-telescope/telescope-file-browser.nvim"
src.git = "https://github.com/nvim-telescope/telescope-file-browser.nvim"

[telescope-project]
fetch.github = "nvim-telescope/telescope-project.nvim"
src.git = "https://github.com/nvim-telescope/telescope-project.nvim"

[telescope-ui-select]
fetch.github = "nvim-telescope/telescope-ui-select.nvim"
src.git = "https://github.com/nvim-telescope/telescope-ui-select.nvim"

[todo-comments]
fetch.github = "folke/todo-comments.nvim"
src.git = "https://github.com/folke/todo-comments.nvim"

[trouble]
fetch.github = "folke/trouble.nvim"
src.git = "https://github.com/folke/trouble.nvim"

[tree-sitter-nu]
fetch.git = "https://github.com/nushell/tree-sitter-nu"
src.git = "https://github.com/nushell/tree-sitter-nu"
src.branch = "main"

[typescript-tools]
fetch.github = "pmizio/typescript-tools.nvim"
src.git = "https://github.com/pmizio/typescript-tools.nvim"

[undotree]
fetch.github = "mbbill/undotree"
src.git = "https://github.com/mbbill/undotree"

[vim-fugitive]
fetch.github = "tpope/vim-fugitive"
src.git = "https://github.com/tpope/vim-fugitive"

[vim-just]
fetch.github = "NoahTheDuke/vim-just"
src.git = "https://github.com/NoahTheDuke/vim-just"

[which-key]
fetch.github = "folke/which-key.nvim"
src.git = "https://github.com/folke/which-key.nvim"
