name: Update Flake Inputs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 3" # 02:00 on Wednesday

jobs:
  update-lockfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.0

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v26

      - name: Update Sources
        run: |
          nix run nixpkgs#nvfetcher
          pushd pkgs/nvim-treesitter
          nix run nixpkgs#nvfetcher
          popd

      - name: Update Lockfile
        run: nix flake update

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update deps"
          commit_user_name: GitHub Actions
